---
- name: copy zabbix to html
  command: >
    cp -r /usr/share/zabbix/ /usr/share/nginx/html

- name: chown files 
  command:
    "{{ item }}"
  with_items:
    - chown -R zabbix.zabbix /etc/zabbix/
    - chown -R zabbix.zabbix /usr/share/nginx/
    - chown -R zabbix.zabbix /usr/lib/zabbix/
    - chmod -R 755 /etc/zabbix/web/
    - chmod -R 777 /var/lib/php/session/
    
- name: start zabbix & nginx & php-fpm
  systemd:
    state:  started
    name:   "{{ item }}"
    enabled: yes
  with_items:
    - zabbix-server.service
    - zabbix-agent.service
    - php-fpm.service
    - nginx