---
- name: Set nginx.conf & php.ini
  copy:
      src:  "{{ item.src }}"
      dest: "{{ item.dest }}"
  with_items:
      - { src: "conf.d/www.conf", dest: "/etc/php-fpm.d/www.conf"}
      - { src: "conf.d/php.ini", dest: "/etc/php.ini"} 
      - { src: "conf.d/default.conf", dest: "/etc/nginx/conf.d/default.conf"}    