---
- name: add zabbix repo
  shell: "rpm -i https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm"

- name: Install Zabbix4.0
  yum: name={{ item }} state=latest
  with_items:
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-agent

- name: set zabbix.conf
  template:
      src: conf.d/zabbix_server.conf
      dest: /etc/zabbix/zabbix_server.conf