---
- name: Install Zabbix4.0
  yum:
    name: "{{ item }}"
    state: present     
  with_items:
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-agent

- name: set zabbix.conf
  copy:
      src: conf.d/zabbix_server.conf
      dest: /etc/zabbix/zabbix_server.conf